### PR TITLE
Update client.go

### PR DESCRIPTION
**Pull request by gunjanmimo**
nsm needs some small correction

### CODE REVIEW

**Comment by leecalcote** [comment]
@gunjanmimo heads-up - https://github.com/layer5io/meshery-nsm/pull/23#pullrequestreview-301365418

**Comment by leecalcote** [comment]
@Harshini-M, it'd be great to get your review on this one.

**Comment by leecalcote** [comment]
@gunjanmimo will you be sure to sign-off your commit and resolve the open conflict in this PR?

Please fix the conflict in this PR, if you can (as opposed to opening another).

**Comment by leecalcote** [comment]
@gunjanmimo will you be sure to sign-off your commit and resolve the open conflict in this PR?

**Comment by leecalcote** [comment]
@Harshini-M will you take a look the conflict in this PR? - https://github.com/layer5io/meshery-nsm/pull/23/conflicts

**Comment by gunjanmimo** [comment]
@leecalcote  sir, I made all the required changes in this https://github.com/layer5io/meshery-nsm/pull/32

**Comment by leecalcote** [comment]
@gunjanmimo it looks like we have conflicts in yaml.go.

@Harshini-M will you take a look and resolve or work with @gunjanmimo to resolve?

**Pull request closed without merging**
