### PR TITLE
Fix badges hyperlink

### PR DESCRIPTION
**Pull request by ArturBa**
Fixed badges and logo hyperlinks.
Fix issue #30

### CODE REVIEW

**Comment by leecalcote** [comment]
Hi @ArturBa thanks so much for this contribution. There's one final step left before merging - https://github.com/layer5io/meshery-nsm/pull/31/checks?check_run_id=277323833

**Comment by ArturBa** [comment]
@leecalcote, sure I will execute this commands today. Will update you when i will be ready ;)

**Comment by ArturBa** [comment]
Sure. Will update when ready ;)

**Comment by ArturBa** [comment]
Now it should be ok ;)

**Pull request merged**
